@startuml

class App
{
public static void main(String[] args)

}
class ReadFile
{
ReadFile()
read()
getdata()
}
class Input
{
    String output;
}
class WriteFile
{
WriteFile()
writeFile()
getCount()
}
App <|-- WriteFile
App <|-- WordCount
App <|-- ReadFile
App <|-- Input

@enduml